name: xiaoming
description: A new Flutter application.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.8
  intl: ^0.17.0
  bloc: ^8.0.2
  http: ^0.13.4
  #  geolocator: ^8.0.1
  #  qr_code_scanner: ^0.7.0
  permission_handler: ^9.2.0
  get: ^4.3.8
  location: ^4.3.0
  fluttertoast: ^8.0.8
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.0.2
  connectivity_plus: ^2.0.2
  jwt_decoder: ^2.0.1
  khmer_date: ^0.0.3
  photo_view: ^0.13.0
  syncfusion_flutter_datagrid: ^20.1.52
  syncfusion_flutter_charts: ^20.1.52
  open_file: ^3.2.1
  syncfusion_flutter_datepicker: ^20.1.52
  #  scrollable_list_tabview: ^0.2.0-nullsafety
  scrollable_positioned_list: ^0.2.3
  search_choices: ^2.0.20
  auto_size_text: ^3.0.0
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.1
  flip_card: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: KhmerOSBattambong
      fonts:
        - asset: assets/fonts/khmeros_battambong.ttf
    - family: KhmerOSMuol
      fonts:
        - asset: assets/fonts/KhmerOS_muol.ttf
    - family: KhmerMPTC
      fonts:
        - asset: assets/fonts/KhmerMPTC.ttf
    - family: KhmerMPTCMoul
      fonts:
        - asset: assets/fonts/KhmerMPTCMoul.ttf
    - family: GroundControl
      fonts:
        - asset: assets/fonts/GroundControl.ttf
    - family: KhmerOSSiemReap
      fonts:
        - asset: assets/fonts/KhmerOSSiemreap.ttf
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/card/
    - assets/images/mptc_logo_l.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
