name: xiaoming
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.8
  intl: ^0.17.0
  bloc: ^8.0.2
  http: ^0.13.4
  #  geolocator: ^8.0.1
  #  qr_code_scanner: ^0.7.0
  permission_handler: ^9.2.0
  get: ^4.3.8
  location: ^4.3.0
  fluttertoast: ^8.0.8
  get_storage: ^2.0.3
  flutter_secure_storage: ^5.0.2
  connectivity_plus: ^2.0.2
  jwt_decoder: ^2.0.1
  khmer_date: ^0.0.3
  photo_view: ^0.13.0
  syncfusion_flutter_datagrid: ^20.1.52
  syncfusion_flutter_charts: ^20.1.52
  open_file: ^3.2.1
  syncfusion_flutter_datepicker: ^20.1.52
  #  scrollable_list_tabview: ^0.2.0-nullsafety
  scrollable_positioned_list: ^0.2.3
  search_choices: ^2.0.20
  auto_size_text: ^3.0.0
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.1
  flip_card: ^0.6.0
  avatars: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: KhmerOSBattambong
      fonts:
        - asset: assets/fonts/khmeros_battambong.ttf
    - family: KhmerOSMuol
      fonts:
        - asset: assets/fonts/KhmerOS_muol.ttf
    - family: KhmerMPTC
      fonts:
        - asset: assets/fonts/KhmerMPTC.ttf
    - family: KhmerMPTCMoul
      fonts:
        - asset: assets/fonts/KhmerMPTCMoul.ttf
    - family: GroundControl
      fonts:
        - asset: assets/fonts/GroundControl.ttf
    - family: KhmerOSSiemReap
      fonts:
        - asset: assets/fonts/KhmerOSSiemreap.ttf
    - family: NiDAFunan
      fonts:
        - asset: assets/fonts/NiDAFunan.ttf
    - family: NiDASowannaphum
      fonts:
        - asset: assets/fonts/NiDASowannaphum.ttf
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/card/
    - assets/images/mptc_logo_l.png
